### ISSUE TITLE
TS212P - problem with qnap_mtd_resize

### ISSUE THREAD

**Issue by giallino64** [amouiche/qnap_mtd_resize_for_bullseye#10]
I am using a TS-212P with Debian Stretch installed. I would like to install Debian Bullseye using the qnap_mtd_resiz.py script but I always get errors. If I use Python 3.5.3 I get

  _File "qnap_mtd_resize.py", line 95
      Raise KeyError(f"No mtd '{name}' device found.")
  Syntax error: invalid syntax_

If I use Python 3.9.4 I get

  _kirkwood-qnap: machine:QNAP TS219 family
  DTB file: kirkwood-ts219-6282.dtb
  Checking: /sbin/flashcp -V
  Checking: /sbin/flash_erase --version
  Checking: /usr/bin/fw_setenv -v
  /usr/bin/fw_setenv: invalid option -- 'v'
  Usage: fw_setenv [OPTIONS]... [VARIABLE]...
  Modify variables in U-Boot environment
  ecc... ecc..._

any suggestions?

**Comment by hartkopp** [comment]
> I am using a TS-212P with Debian Stretch installed. I would like to install Debian Bullseye using the qnap_mtd_resiz.py script but I always get errors. If I use Python 3.5.3 I get

> any suggestions?

Yes. I would suggest to upgrade from Stretch to Buster first.

This file ...

https://github.com/amouiche/qnap_mtd_resize_for_bullseye/blob/master/bullseye_upgrade.md

... gives a hint, what to do - just replace buster with stretch AND bullseye with buster from that example ...

**Comment by giallino64** [comment]
perfect. Thank you

**Comment by amouiche** [comment]
closing
