### ISSUE TITLE
TS-119+: Failed: no information found with dmesg

### ISSUE THREAD

**Issue by zoof** [amouiche/qnap_mtd_resize_for_bullseye#25]
Hi,

I did the dry run and got the following:
```
$ sudo ./qnap_mtd_resize.py --dry-run

[Check of the QNAP model and see if supported]
kirkwood-qnap: machine: QNAP TS219 family
DTB file: kirkwood-ts219-6282.dtb
Checking: flashcp -V
Checking: flash_erase --version
Using 'u-boot-tools' package

[find on which MTD device partitions are currently mounted]
Failed: no information found with dmesg
```

I am currently running Buster.  neofetch shows:
```
       _,met$$$$$gg.          user@localhost 
    ,g$$$$$$$$$$$$$$$P.       ------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 10 (buster) armv5tel 
 ,$$P'              `$$$.     Host: QNAP TS219 family 
',$$P       ,ggs.     `$$b:   Kernel: 4.19.0-20-marvell 
`d$$'     ,$P"'   .    $$$    Uptime: 53 days, 21 hours, 56 mins 
 $$P      d$'     ,    $$P    Packages: 664 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.0.3 
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/1 
 Y$$.    `.`"Y$$$$P"'         CPU: Feroceon 88FR131 rev 1 (v5l) (1) @ 2.000GHz 
 `$$b      "-.__              Memory: 114MiB / 501MiB 
  `Y$$
   `Y$$.                                              
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
```

**Comment by amouiche** [comment]
Hello.

May be your "relative" high uptime (53 days) was enough to truncate was
we are looking from the 'dmesg' output.

Can you:
- reboot and run again the ./qnap_mtd_resize.py script
- and if it still fails, copy/paste in a email the 'dmesg' command
output

Regards,
Arnaud

**Comment by zoof** [comment]
Ah, that was the problem.  The dry run now works fine.

Has anyone done this with a 119+ yet?

**Comment by amouiche** [comment]
On Fri, 2022-05-20 at 05:13 -0700, zoof wrote:
> Ah, that was the problem. The dry run now works fine.
> Has anyone done this with a 119+ yet?

It was not reported Yet. there was a 119P+ which as the same hardware
description than your (kirkwood-ts219-6282.dtb)
Finally, there are not so many differences between the QNAP ARM
models...

**Comment by zoof** [comment]
Thank you for the response.  My concern is if there is an unanticipated failure.  While I have some basic skills with hardware, I wouldn't look forward to modding it with a serial cable for recovery purposes -- this is our home NAS.

**Comment by amouiche** [comment]
On Fri, 2022-05-20 at 06:33 -0700, zoof wrote:
> Thank you for the response. My concern is if there is an
> unanticipated failure. While I have some basic skills with hardware,
> I wouldn't look forward to modding it with a serial cable for
> recovery purposes -- this is our home NAS.

I understand your position.
So far, those who had problemes:
- jumped to bulleyes before resizing (now fixed)
- performed QNAP recovery after resizeing (now fixed)
- had manual uboot variable changes (and already had a serial console
to perform those changes)

None of the issues was due to a hardware variant.

Arnaud

**Comment by zoof** [comment]
> Hi @zoof , I have a TS-119P+ which converted from Debian Buster like charm. Is there really a TS-119+ - or did you just miss the ''P" ? ;-)

Ah, I think you are right -- I have the same model...

> None of the issues was due to a hardware variant.

Ok, that makes me feel much better.  Now I just have to get my courage up!

**Comment by zoof** [comment]
I finally took the plunge and it worked beautifully!

**Comment by hartkopp** [comment]
Excellent! The scripts from @amouiche really help to keep that old hardware up to date with features and security. That's a real step for sustainability and reduces e-waste <3
