### ISSUE TITLE
Successful with QNAP TS-212P

### ISSUE THREAD

**Issue by vincele** [amouiche/qnap_mtd_resize_for_bullseye#37]
Hello,
it went smoothly on my first TS-212P, I went from stretch to buster then bullseye, now fully up-to-date, including bullseye's `5.10.0-20-marvell` kernel.

The second one is currenty going through the same process.

This old hardware will not go to the trash !
Thanks a lot !

**Comment by vincele** [comment]
Second one is updated too, not a single problem along the way.

They will export a `RAID10,far2` array as iSCSI targets for my homelab proxmox.

I will setup `popularity-contest` on each one, to let upstream know this arch is still being actively used in the field !

**Comment by amouiche** [comment]
thank you for your report !
