### ISSUE TITLE
looking for flashcp and flash_erase in /sbin instead of /usr/sbin; dmesg in /usr/bin instead of /bin

### ISSUE THREAD

**Issue by docteurmystere** [amouiche/qnap_mtd_resize_for_bullseye#4]
see topic. on my system (debian buster mainline, pretty much stock except for a few boot scripts, on TS-421) the two binaries were found in /usr/sbin. creating a symlink solves this problem. same goes with dmesg, but the other way around.

**Comment by docteurmystere** [comment]
update: actually every shell command is inverted on my system. what the script is searching in /sbin is actually in /usr/sbin and viceversa.

**Comment by amouiche** [comment]
various tools (flash_cp) are now used from PATH (with PATH updated to add /sbin and /usr/sbin)
