### ISSUE TITLE
Debian Backworm

### ISSUE THREAD

**Issue by Schnup89** [amouiche/qnap_mtd_resize_for_bullseye#40]
Hello all,

is it possible to flash Debian backworm with the increased flash partitions?

**Comment by cavokz** [comment]
I already upgraded my qnap from Bullseye to Bookworm, everything looks fine. The flash partitions were already increased by this tool.

**Comment by Schnup89** [comment]
Thank you very much! Bullseye update is running right now, if that finished successfully I will go for Bookworm

**Comment by Conan179** [comment]
What did you enter in the source.list? I get this message when I try to do apt update:
`Ign:1 http://security.debian.org/debian-security boockworm-security InRelease
Fehl:2 http://security.debian.org/debian-security boockworm-security Release
  404  Not Found [IP: 2a04:4e42:8e::644 80]
Ign:3 http://deb.debian.org/debian boockworm InRelease
Fehl:4 http://deb.debian.org/debian boockworm Release
  404  Not Found [IP: 2a04:4e42:8e::644 80]
Paketlisten werden gelesen… Fertig
E: Das Depot »http://security.debian.org/debian-security boockworm-security Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
E: Das Depot »http://deb.debian.org/debian boockworm Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktivier`

**Comment by Schnup89** [comment]
Hi, funktioniert bei mir mit folgender source.list:


deb http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
deb http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware
deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware

**Comment by Conan179** [comment]
Ich hab meinen Fehler gefunden, ich hab boo**C**kworm eingetragen, stats bookworm, peinlich peinlich.
