### ISSUE TITLE
option to skip bootargs step

### ISSUE THREAD

**Issue by docteurmystere** [amouiche/qnap_mtd_resize_for_bullseye#6]
i have a heavily customized uboot variable set, and the script is unable to parse them because the cp.l instructions are not directly in the bootcmd. i know what to change at reboot via serial console, but the script just exit(1)s on me without proceeding (i'm still in dry run). any chance to have an option to skip this particular step for those in my situation?

edit: better yet, separate skipping bootcmd update and bootargs update. ^^"

edit2: attaching fw_printenv output for reference.
[qEnv.txt](https://github.com/amouiche/qnap_mtd_resize_for_bullseye/files/7277575/qEnv.txt)

**Comment by docteurmystere** [comment]
attaching possible patch. i am a noob at git, my apologies.
[patch.txt](https://github.com/amouiche/qnap_mtd_resize_for_bullseye/files/7280549/patch.txt)

**Comment by amouiche** [comment]
The feature to skip some bootargs is now supported
